import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
		<div className="flex gap-8 flex-col gap-8 row-start-2 items-center justify-center p-1">
		 <header className="row-start-3 flex gap-6 flex-wrap items-center justify-center">
		   <a
            className="border border-solid border-transparent transition-colors flex items-center justify-center bg-foreground text-background gap-2 hover:bg-[#383838] dark:hover:bg-[#75715E] text-sm sm:text-base h-10 sm:h-10 px-4 sm:px-5"
            href="https://en.wikipedia.org/wiki/Horse"
            rel="noopener noreferrer"
          >
            horse pages
          </a>
		 </header>
		</div>
        {children}
      </body>
    </html>
  );
}
